/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ludii_cpp_ai_LudiiCppAI */

#ifndef _Included_ludii_cpp_ai_LudiiCppAI
#define _Included_ludii_cpp_ai_LudiiCppAI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ludii_cpp_ai_LudiiCppAI
 * Method:    nativeSelectAction
 * Signature: (Lgame/Game;Lother/context/Context;DII)Lother/move/Move;
 */
JNIEXPORT jobject JNICALL Java_ludii_1cpp_1ai_LudiiCppAI_nativeSelectAction
  (JNIEnv *, jobject, jobject, jobject, jdouble, jint, jint);

/*
 * Class:     ludii_cpp_ai_LudiiCppAI
 * Method:    nativeInitAI
 * Signature: (Lgame/Game;I)V
 */
JNIEXPORT void JNICALL Java_ludii_1cpp_1ai_LudiiCppAI_nativeInitAI
  (JNIEnv *, jobject, jobject, jint);

/*
 * Class:     ludii_cpp_ai_LudiiCppAI
 * Method:    nativeCloseAI
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ludii_1cpp_1ai_LudiiCppAI_nativeCloseAI
  (JNIEnv *, jobject);

/*
 * Class:     ludii_cpp_ai_LudiiCppAI
 * Method:    nativeSupportsGame
 * Signature: (Lgame/Game;)Z
 */
JNIEXPORT jboolean JNICALL Java_ludii_1cpp_1ai_LudiiCppAI_nativeSupportsGame
  (JNIEnv *, jobject, jobject);

/*
 * Class:     ludii_cpp_ai_LudiiCppAI
 * Method:    nativeStaticInit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ludii_1cpp_1ai_LudiiCppAI_nativeStaticInit
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
